config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/profile'
  get 'userinfo', to: 'pages#userinfo'
  get 'postinfo', to: 'pages#postinfo'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations'
  }
  # devise_for :users, controllers: { confirmations: 'users/confirmations' }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :posts do
    resources :comments
  end
  # get 'home' to: 'pages#home'
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # delete '/posts/:id', to: 'posts#destroy', as: 'post  '
  # Defines the root path route ("/")

  resources :users, only: %i[create update edit]
  resources :post, only: %i[create update edit destroy]
  resources :posts do
    member do
      patch 'upvote'
      patch 'downvote'
    end
  end

  get '/posts/:id/upvote', to: 'posts#upvote'
  get 'post/:id/downvote', to: 'posts#downvote'

  post '/posts/:id/like', to: 'posts#like', as: 'like_post'

  get 'mypricing', to: 'home#mypricing'
  get 'userinformation', to: 'home#userinformation'

  # stipe
  # stripe listen --forward-to localhost:3000/stripe/webhook
  post 'stripe/webhooks', to: 'stripe/webhooks#create'
  get 'pricing', to: 'stripe/checkout#pricing'
  post 'stripe/checkout', to: 'stripe/checkout#checkout'
  get 'stripe/checkout/success', to: 'stripe/checkout#success'
  get 'stripe/checkout/cancel', to: 'stripe/checkout#pricing'
  post 'stripe/billing_portal', to: 'stripe/billing_portal#create'

  # facebook login
  # user_{provider}_omniauth_authorize_path
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'

  root 'pages#home'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def mypricing1
    # Render the pricing.html.erb file
    render :mypricing
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/mypricing.html.erb
<br><br><!-- -->
<div class="container card " ,style="background-color:black">
    <br> 
<section id="">
    <h2 class=" text-center">A Plan for Every User Needs</h2>
    <p class="text-center">Simple and affordable price plans for you.</p>

    <div class="row">
        <div class="column col-lg-4 col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3>Basic Plan   <i class="fa-solid fa-user"></i></h3>
                </div>
                <div class="card-body">
                    <h2> Rs 500/mon</h2>
                    <p>Access: Read Post and Comments</p>
                    <p>Access: Can create/edit own New Comment/Post</p>
                    <p>No Access : to delete/edit others post and Comments</p>
                    <div class="d-grid gap-2">


                        <%= link_to  'Subscribe Now!',pricing_path, class:"btn btn-lg  btn-outline-dark"%>
                    </div>
                </div>
            </div>
        </div>
        <div class=" column col-lg-4 col-md-6 ">
            <div class="card">
                <div class="card-header">
                    <h3>Professional Plan  <i class="fa-solid fa-user-shield"></i></h3>
                </div>
                <div class="card-body">
                    <h2>Rs 1000 / mo</h2><p>Access: Read Post and Comments</p>
                    <p>Access: Can create New Comment/Post</p>
                    <p>Access:Edit/delete owns post/comment</p>
                    <p>Access : to Edit others posts</p>
                    <div class="d-grid gap-2">
                        <%= link_to  'Subscribe Now!',pricing_path, class:"btn btn-lg  btn-dark"%>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="column col-lg-4 col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Elite Plan <i class="fa-solid fa-user-gear"></i> </h3>
                </div>
                <div class="card-body">
                    <h2>Rs 2000 / mo</h2>
                    <p>Access: Read Post and Comments</p>
                    <p>Access: Can create New Comment/Post</p>
                    <p>Access : can delete/edit others post and Comments</p>
                    <div class="d-grid gap-2">
                        <%= link_to  'Do it now !',pricing_path, class:"btn btn-lg  btn-dark"%>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
</div>

app/views/home/userinformation.html.erb
<div class="container glass1">
  <!-- <div class="container">
    <% if current_user.confirmed? %>
     <button class="btn">   <p style="Color:green"> ✔ Confirmed Account</p></button>
    <%else%>
    <button class="btn btn-danger"><p style="Color:red"> ❗ Not Confirmed</p></button>
    <%end%>
    </div> -->
<div class="container">
  <br />
  <% if current_user.userimage.present? %>
  <div class="text-center" >
    <%= image_tag (current_user.userimage.url) ,alt: 'User Image' ,class:"
    img-thumbnail img-fluid",style:"height:300px;width:300px;
    border-radius:100%"%>
    <p>
      <em><b>Profile Image</b></em>
    </p>
  </div>
  <% else %>
  <div class="text-center ">
    <%= image_tag "default_image.jpg" ,class:" img-thumbnail
    img-fluid",style:"height:300px;width:300px; border-radius:100%"%>
    <p>
      <em><b>Default Profile Image</b></em>
    </p>
  </div>
  <%end%>
</div>
<div class="container">
  <div class="card border-info">
    <div class="card-header text-center border-info">
      <h3>Account Information</h3>
    </div>

    <div class="card-body">
      <h4><b>User Name:</b> <%=current_user.name%></h4>
      <h4><b>Email:</b> <%= current_user.email %></h4>
      <h4><b>Role: </b><%=current_user.role%></h4>

      <h5><b>Account created at: </b><%=current_user.created_at%></h5>
      <div class="container card">
        <br />
        <p><b>Stripe customer id: </b><%= current_user.stripe_customer_id %></p>
        <p><b>Plan: </b><%=current_user.plan%></p>

        <p>
          <b>Subscription Status: </b> <%= current_user.subscription_status%>
        </p>
        <p>
          <b>Subscription Ends at: </b> <%= current_user.subscription_ends_at%>
        </p>
      </div>
    </div>
    <div class="container text-center">
      <%= button_to ' Go to Billing Portal', stripe_billing_portal_path,class: "
      btn btn-dark fa-regular ",data:{turbo:'false'} %> <br />
      <%= link_to " Edit Account" ,edit_user_registration_path ,class:"btn
      btn-outline-dark fa-solid fa-user-pen" %> <br /><br />
    </div>
  </div>
</div>
<br>
</div>