config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/profile'
  get 'userinfo', to: 'pages#userinfo'
  get 'postinfo', to: 'pages#postinfo'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations'
  }
  # devise_for :users, controllers: { confirmations: 'users/confirmations' }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :posts do
    resources :comments
  end
  # get 'home' to: 'pages#home'
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # delete '/posts/:id', to: 'posts#destroy', as: 'post  '
  # Defines the root path route ("/")

  resources :users, only: %i[create update edit]
  resources :post, only: %i[create update edit destroy]
  resources :posts do
    member do
      patch 'upvote'
      patch 'downvote'
    end
  end

  get '/posts/:id/upvote', to: 'posts#upvote'
  get 'post/:id/downvote', to: 'posts#downvote'

  post '/posts/:id/like', to: 'posts#like', as: 'like_post'

  get 'mypricing', to: 'home#mypricing'
  get 'userinformation', to: 'home#userinformation'

  # stipe
  # stripe listen --forward-to localhost:3000/stripe/webhook
  post 'stripe/webhooks', to: 'stripe/webhooks#create'
  get 'pricing', to: 'stripe/checkout#pricing'
  post 'stripe/checkout', to: 'stripe/checkout#checkout'
  get 'stripe/checkout/success', to: 'stripe/checkout#success'
  get 'stripe/checkout/cancel', to: 'stripe/checkout#pricing'
  post 'stripe/billing_portal', to: 'stripe/billing_portal#create'

  # facebook login
  # user_{provider}_omniauth_authorize_path
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/users/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'

  root 'pages#home'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 100_000 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  # has_many :users, through: :comments
  has_many :users

  has_noticed_notifications model_name: 'Notification'

  # has_many :notifications, through: :user, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :likers, through: :likes, source: :user

  mount_uploader :avatar, AvatarUploader
  validates :avatar, file_size: { less_than: 2.megabytes }

  acts_as_votable

  # has_rich_text :body

  # scope :soft_delete, -> { where(deleted_at: Time.current) }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include CanCan::ControllerAdditions

  load_and_authorize_resource

  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json

  def index
    # @posts = Post.all.order(created_at: :desc)
    @posts = Post.page(params[:page]).per(3).order(created_at: :desc)

    # @post = Post.order(:posts).page(params[:posts]).per(10)
  end

  # def upvote
  #   @post = Post.find(params[:id])
  #   if current_user.voted_up_on? @post
  #     @post.unvote_by current_user
  #   else
  #     @post.upvote_by current_user
  #   end
  #   render 'vote.js.erb'
  # end

  # def downvote
  #   @post = Post.find(params[:id])
  #   if current_user.voted_down_on? @post
  #     @post.unvote_by current_user
  #   else
  #     @post.downvote_by current_user
  #   end
  #   render 'vote.js.erb'
  # end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(view: @post.view + 1)
    # @comments = @post.comments.order(created_at: :desc)
    @comments = @post.comments.order(created_at: :desc).paginate(page: params[:page], per_page: 3)

    mark_notifications_as_read
    # views=@post.view+1
    # @post.view=views
    # @post.save
    # Get the post's likes.
    # Get the post's likes, if they exist.
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  # POST /posts or /posts.json
  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        PostMailer.with(user: current_user, post: @post).post_created.deliver
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # def like
  #   @post = Post.find(params[:id])
  #   @post.increment!(:likes_count)
  #   render json: { likes_count: @post.likes_count }

  # end
  def like
    # binding.pry

    @post = Post.find(params[:id])
    like = @post.likes.find_by(user: current_user)

    if like
      like.destroy
      @post.decrement!(:likes_count)
    else
      @post.likes.create(user: current_user)
      @post.increment!(:likes_count)
    end

    respond_to do |format|
      # format.html { redirect_to posts_url }
      # format.json { render json: { likes_count: @post.likes_count } }
      format.json { render json: { likes_count: @post.likes_count }.to_json }
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    # @post.soft_delete
    respond_to do |format|
      format.html { redirect_to posts_url, alert: 'Post was successfully deleted' }
      format.json { head :no_content }
    end
  end

  # def truncate_post_body(post)
  #   post.body.truncate(150)
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def mark_notifications_as_read
    return unless current_user

    notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
    notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :avatar, :remove_avatar, :avatar_cache)
    # params.require(:post).permit(:title, :body, :avatar).tap do |whitelisted|
    #   whitelisted[:body] = params[:post][:body]
    # end
  end
end

app/views/posts/_downvote_link.html.erb
<%= content_tag "div", id: "downvote-#{post.id}" do %>
  <%= link_to downvote_post_path(post), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <% if current_user.voted_down_on? post %>
      <i class="far fa-thumbs-down" style="color: red;"></i>
      unvote
    <% else %>
      <i class="far fa-thumbs-down"></i>
      downvote
    <% end %>
  <% end %>
<% end %>

app/views/posts/_errors.html.erb
<% if post.errors.any?%>
    <ul class="glass2">
        <% post.errors.full_messages.each do |message| %>
            <li class="text-center text-danger"%>
                <%= message %>

            </li>
            <% end %>

    </ul>
<% end %>

app/views/posts/_form.html.erb
<style>
  ::placeholder {
    color: black;
  }
</style>
<%= form_with(model: post) do |form| %>
  <!-- <% if post.errors.any? %>
    <div style="color: red">
      <h5><%= pluralize(post.errors.count, "Errors") %> : Please check before continuing </h5>
    </div>
  <% end %> -->
<br>
<%# <label style="text-align:left;font-align:left; ">Title</label> %>
<br>
  <div style="text-align:left; justify-content:left,font-align:left">
  <label ><em><b>Title*</b></em></label>
    <%= form.text_field :title ,placeholder:"Title of your post goes here..",class:"form-control"%>
    <br>
    <%= render  'errors',post:post %>
  </div>
  <br>

  <div style="text-align:left; justify-content:left,font-align:left">
<label> <em><b>Body*</b></em></label>
    <%= form.text_area :body ,placeholder:"Body of your post goes here..." ,class:"form-control" ,rows: 9 %>
  <br>
    <%= render  'errors',post:post %>
  </div> 
<br>

  <div class="form-group">
    <div style="text-align:left; justify-content:left,font-align:left ">
    <label><em><b>Upload Image </b></em></label></div>
    <%= form.file_field :avatar, class: 'form-control' %>
  </div>

<br>
  <div class="d-grid gap-2">
   
    <%= form.submit 'Submit', class:"btn btn-lg btn-outline-success"%>
  
  </div>
<% end %>

app/views/posts/_like_count.html.erb
<%= content_tag "div", id: "like-count-#{post.id}" do %>
  <%= post.cached_votes_score %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

<div class="container">
<div class=" card text-center p-3 mb-2 bg-light-subtle text-emphasis-info border-success glass1">
  <p style="text-align:left;font-size:1.6rem;">
    <strong class="intro", style="font-size:1.5rem">Title:  </strong>
    <%= post.title %>

  </p>

  <div style="text-align:left;font-size:1.3rem">    
  <strong class="intro", style="font-size:1.5rem">Body:   </strong>
    <%= post.body %>
  </div>
  <br>
  
  <p ><h6 class="fa fa-solid"><i class="fa-solid fa-users"></i> <%= pluralize(post.view,"view") %></h6></p>
  <p> <h6 class="fa fa-solid"> <i class="fa-solid fa-user-secret  " style="color: #1f5145"></i> Posted by:
    
    <% if post.user.userimage.present? %>
          <%= image_tag (post.user.userimage.url), class:" img-fluid",style:"height:50px;width:50px; border-radius:100%"%>

        <% else %>
          <%= image_tag "default_image.jpg" ,class:"img-fluid",style:"height:50px;width:50px; border-radius:100%"%>   
        <%end%>
    <%= link_to post.user.name,user_path(post.user) %></h6>
    </p>
    <p class="fa fa-solid fa-clock"> Creation Date :  <%=
      time_ago_in_words(post.created_at)%> </p>
</div>
</div>
</div>

app/views/posts/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{post.id}" do %>
  <%= link_to upvote_post_path(post), method: :patch, remote: true, data: { disable_with: "voting..." } do %>
    <% if current_user.voted_up_on? post %>
      <i class="far fa-thumbs-up " style="color: green;"></i>
      unvote
    <% else %>
      <i class="far fa-thumbs-up"></i>
      upvote
    <% end %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class=" makeme card text-center p-3 mb-2 bg-info-subtle text-emphasis-info border-info " >
<div class="container glass4 ">
  <br>
<div class ="card-header">
<h1> <i class="fa-solid fa-pen-to-square fa-xl" style="color: #10f;"></i> Editing post</h1>
</div>
<br>
<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "  Show this post", @post  ,class: "btn btn-lg btn-outline-secondary fa-regular fa-eye "%> | |
  <%= link_to "  Back to posts", posts_path ,class: "btn btn-lg btn-outline-primary fa-solid fa-backward" %>
  <br>
  <br>
  <%= button_to "  Delete this post", post_path(@post), method: :delete ,remote: true, data: {turbo_confirm: "Are you sure you want to delete??"},class:"btn btn-lg btn-outline-danger fa-solid fa-trash"%>

</div>
<br>
</div>
</div>

app/views/posts/index.html.erb
<!-- Adjust the path accordingly -->

<p style="color: green"><%= notice %></p>
<div
  class="indexview card text-center p-3 mb-2 text-emphasis-info border-info glass2"
>
  <div class="container">
    <div class="card-header jumbotron">
      <br />
      <h1>All Posts <i class="fa-thin fa-face-awesome"></i></h1>
      <br />
    </div>
    <br />

    <div id="posts">
      <% @posts.each do |post| %> <%= render post , post_body: post.body%>

      <div class="container text-center">
        <b>
          <p id="countlike_<%= post.id %>">Likes: <%= post.likes_count %></p>
        </b>
        <% if (can? :like,Post)  && current_user.role!='nil'  %>
        <%= button_to "Like This Post", like_post_path(post), id: "like_post_pls_#{post.id}",
          data: { post_id: post.id, state: 'like' }, method: :put, remote: true,
          class: "like-button btn btn-dark" %>
          <%end%>
        <br>
      </div>



      <!-- <% if current_user %>
            <br>
            <%= render 'posts/like_count' , post: post %>
              <%= render 'posts/upvote_link' , post: post %>
                <% end %> -->

      <p>
        <%= link_to " Show this post" , post, class:"btn btn-lg btn-outline-info
        fa-regular fa-eye mybtn" %>
      </p>
      <% end %>
    </div>
    <br />
    <div class="pagination justify-content-center gonext">
      <%= paginate @posts %>
    </div>
    <br />
    <% if(can? :create ,Post)%>
    <div class="d-grid gap-2">
      <%= link_to " New post" , new_post_path, class:"btn btn-lg
      btn-outline-primary fa-solid fa-feather-alt mybtn" %>
    </div>
    <%end%>
  </div>
  <br />

  <div class="container d-flex d-grid gap-5" ,style="justify-content:right">
    <a href="#comehere">
      <button
        class="btn btn-outline-info btn-lg rounded-pill fa fa-circle-up share-icon"
      ></button>
    </a>
  </div>
</div>



<script>
  $(document).ready(function () {
  $(document).on("click", "[id^=like_post_pls_]", function (event) {
    event.preventDefault();
    var postId = $(this).data("post-id");
    var button = $(this);

    $.ajax({
      url: "/posts/" + postId + "/like",
      type: "post",
      data: { like_id: true },
      beforeSend: function (xhr) {
        xhr.setRequestHeader(
          "X-CSRF-Token",
          $('meta[name="csrf-token"]').attr("content")
        );
      },
      success: function (data) {
        if (button.data("state") === "like") {
          // Toggle the state to "dislike"
          button.data("state", "dislike");
          button.text("Dislike This Post");
        } else {
          // Toggle the state back to "like"
          button.data("state", "like");
          button.text("Like This Post");
        }
        var likesCountId = "countlike_" + postId;
        $("#" + likesCountId).text("Likes: " + data.likes_count);
      },
      error: function (error) {
        console.log("AJAX request failed");
        console.log(error);
      },
    });
  });
});

</script>

app/views/posts/new.html.erb
<div class=" makeme card text-center p-3 mb-2 bg-primary-subtle text-emphasis-info border-info ">

<div class="container">
<div class ="card-header">
<h1> <i class="fa-solid fa-feather-alt " style="color: #328f95;"></i> New Post</h1>
</div>
<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "  Back to posts", posts_path,class:"btn btn-lg btn-outline-secondary fa-solid fa-backward" %>
</div>

</div>
</div>

app/views/posts/show.html.erb
<br />
<div class="container glass2">
  <br />
  <%= render @post %> <% if @post.avatar? %>
  <div class="container card text-center">
    <%= image_tag (@post.avatar.url) ,alt: 'Post Image'%>
  </div>
  <%end %>
  <br />
  <!-- <div class="container text-center">
    <b> <p id="countlike">Likes: <%= @post.likes_count %></p></b>

    <%= button_to "Like This Post", like_post_path(@post), id: 'like_post_pls',
    data: { post_id: @post.id, state: 'like' }, method: :put, remote: true,
    class: "like-button btn btn-dark" %>
  </div> -->

  <h6 class="text-center">
    <br />
    <%= pluralize(@post.comments.distinct.count(:user_id), 'user' ) %> commented
    on this Post.
  </h6>
  <br />

  <br />
  <div class="text-center">
    <% if current_user && (can? :edit ,@post)%> <%= link_to " Edit this post" ,
    edit_post_path(@post) , class:"btn btn-lg btn-outline-dark fa-regular
    fa-pen-to-square"%> | <%end%> <%= link_to " Back to posts" , posts_path ,
    class:"btn btn-lg btn-outline-warning fa-solid fa-backward" %>
    <br />
    <br />
  </div>
</div>
<br />
<h1 class="text-center" ,style="text-color:white"><b> ✉ Comments</b></h1>
<div class="container glass2">
  <br />
  <% if current_user%> <%= render 'comments/form' , post: @post,comment:
  @post.comments.build ,submit_label: "Reply" %> <%end%>
  <br />

  <% if @comments.any? %> <% @comments.order(created_at: :desc).first(5).each do
  |comment| %> <%= render 'comments/comment', post: @post, comment: comment %>
  <% end %>
  <div class="pagination justify-content-center"><%= paginate @comments %></div>
  <% else %>
  <p>No comments yet.</p>
  <!-- <p> <a href="".style="text-decoration:none;">SignUp</a> Now & Do comments..!</p> -->
  <% end %>
</div>
<br /><br />
<div class="contaier justify-content-right">
  <div class="container d-flex d-grid gap-5" ,style="justify-content:right">
    <a href="#comehere">
      <button
        class="btn btn-outline-primary share-icon btn-lg rounded-pill fa fa-circle-up"
      ></button>
    </a>
  </div>
</div>

<!-- ajax implementation -->
<!-- 
<script>
  $(document).ready(function () {
    $(document).on("click", "#like_post_pls", function (event) {
      event.preventDefault();
      var postId = $(this).data("post-id");
      var button = $(this);

      $.ajax({
        url: "/posts/" + postId + "/like",
        type: "post",
        data: { like_id: true },
        beforeSend: function (xhr) {
          xhr.setRequestHeader(
            "X-CSRF-Token",
            $('meta[name="csrf-token"]').attr("content")
          );
        },
        success: function (data) {
          if (button.data("state") === "like") {
            // Toggle the state to "dislike"
            button.data("state", "dislike");
            button.text("Dislike This Post");
          } else {
            // Toggle the state back to "like"
            button.data("state", "like");
            button.text("Like This Post");
          }

          console.log("AJAX request succeeded");
          $("#countlike").text("Likes: " + data.likes_count);
        },
        error: function (error) {
          console.log("AJAX request failed");
          console.log(error);
        },
      });
    });
  });
</script> -->

app/views/posts/vote.js.erb
document.getElementById("like-count-<%= @post.id %>").innerHTML = "<%= j render "posts/like_count", post: @post %>";
document.getElementById("downvote-<%= @post.id %>").innerHTML = "<%= j render "posts/downvote_link", post: @post %>";
document.getElementById("upvote-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";